services:
  # PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-store-php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./fixtures:/var/www/html/fixtures
    networks:
      - api-store-network
    depends_on:
      - mysql

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: api-store-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - api-store-network

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: api-store-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: store_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: store_user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - api-store-network

networks:
  api-store-network:
    driver: bridge

volumes:
  mysql_data:
